### ISSUE TITLE
Unable to install plugin from repositories

### ISSUE THREAD

**Issue by tawrahim** [gdelmas/IntelliJDashPlugin#13]
I was unable to install due to the following error message

```
Plugin Dash was not installed: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by mingyue1991** [comment]
i tried every solution ,but finally failed~still "nothing to show",who can tell me why?
i tried following
1.uncheck use secure connection
2.check auto-detect proxy setting
3.try other version of android studio

**Comment by gdelmas** [comment]
What was the error message? Can you install other plugins from the repositories? This is probably a problem with the IDE.
