### ISSUE TITLE
Search in all Docsets without Language/Context filtered results

### ISSUE THREAD

**Issue by ionos** [gdelmas/IntelliJDashPlugin#28]
Hi,

Currently the Dash-plugin seems to be recommending the Python docset when invoked from PyCharm. For PyQt projects, this means whenever the user searches for a Qt term, she/he has to manually select the Qt-docset (or "None" for no scope constraints) in order to get to the Qt documentation.

Thus a way to disable or configure the context sensitive search would improve the usability in this scenario, maybe by allowing the user to select a profile for contexts.

Thank you,
Clemens

![screen shot 2014-07-27 at 7 51 47 am](https://cloud.githubusercontent.com/assets/29365/3713834/f1da598a-1586-11e4-8722-247c6b3446f8.png)

**Comment by solidfox** [comment]
I'd like to second the request for a preference to set the context in which to search. This is, however, duplicating the search profiles feature of dash in which you can set which docsets are to be searched by default when Dash is invoked from PyCharm (using any method). Thus I would much prefer a plugin that didn't touch the filter and left that to my own Dash prefs.

**Comment by tru** [comment]
I am guessing this is somewhat related: When installing and using this plugin in CLion it defaults to ObjectiveC scope (guessing it's because it's related to AppCode?) It should default to C++ in CLion or be configurable.

**Comment by gdelmas** [comment]
it is not related. i opened a new issue. thanks for reporting.

**Comment by Kapeli** [comment]
> so far no other user has expressed the need to search for unfiltered results. the first version of the plugin did this. if there is need for that i will add it.

If you can, I highly recommend that you add it. Dash has grown a lot and it's impossible for plugins to support all the user-contributed docsets and so on. It would be great to give users an option of managing their own docsets using search profiles in Dash.

**Comment by Kapeli** [comment]
Any ETA? I've had a few users complain about issues caused by this (e.g. the plugin requesting the HTML docset only while it should have requested Ionic).

**Comment by gdelmas** [comment]
sadly i have very little time at the moment. i hope to have the next version ready in some month.

in the meanwhile configuring the ide as described [here](https://github.com/gdelmas/IntelliJDashPlugin/issues/28#issuecomment-50283439) will search all docsets.

**Comment by spicemix** [comment]
I got the workaround to work, thanks. But I'd also vote for a fix, as selecting e.g. "ng-submit" is a bit difficult compared to how I think this is supposed to work.

**Comment by blackxored** [comment]
I second this even though it's ages old.

**Comment by shamilovtim** [comment]
I believe my issue was related here:
https://github.com/gdelmas/IntelliJDashPlugin/issues/64

**Comment by gdelmas** [comment]
i am currently implementing this feature.

**Comment by gdelmas** [comment]
the feature is finally released
