### ISSUE TITLE
Windows Compatibility for Zeal

### ISSUE THREAD

**Issue by WoLpH** [gdelmas/IntelliJDashPlugin#36]
Is there any support for using Zeal under Windows? I find it to work nicer (especially since I can fork and modify Zeal myself) than Velocity.

**Comment by WoLpH** [comment]
By default it's just a package that you download and run from a random directory.

The 2 options I can think of:
 - check for the existance of `%userprofile%/AppData/Local/zeal/docsets`
 - check if zeal.exe is running

**Comment by gdelmas** [comment]
if it is not running. what would be the way to invoke it?

**Comment by WoLpH** [comment]
As far as I know the only way is to call the command (i.e. "zeal.exe").
In this case that would be "zeal.exe --query <QUERY>"

If adding "zeal.exe" to the PATH is the best option that would work too,
although a configurable path would be more convenient of course :)

**Comment by gdelmas** [comment]
assuming users are putting it in PATH might be to much. also the plugin should not need a configuration dialog. maybe you might add [dash-plugin:// scheme](http://kapeli.com/dash_plugins) support to zeal. in this case it would work without modifying the plugin.

**Comment by WoLpH** [comment]
I kind of doubt that actually, adding a program to your PATH is something
you can change relatively easy by modifying the system settings. Adding a
custom url scheme requires modifying the register.

As long as Zeal doesn't have an installer this will be a bit of a pain I
suppose... I will create an upstream pull-request however.

As for supporting url schemes, I would recommend just using dash:// as a
default since both Velocity (Windows) and Dash (OS X) that.
Not sure about the dash-plugin:// scheme but Velocity reponds to both
anyhow so the simpler one might be better.

**Comment by gdelmas** [comment]
neither step, adding to path or registry, should be done by the user. i would recommend that zeal registers the url scheme on startup. this way no installation is needed.

please do NOT use dash:// scheme. it was the old way how plugins used to call dash and does not support multiple docsets. multiple docset filters is an integral part for good search results. zeal added support for this lately. of course it is possible to add dash:// scheme additionally to support other older plugins.

**Comment by trollixx** [comment]
Since version [0.1.0](https://github.com/zealdocs/zeal/releases/tag/v0.1.0) Zeal supports `dash-plugin:` protocol on Windows and Linux, and should be 100% compatible with Dash. So, now there's no need to do anything Zeal specific in this IntelliJ plugin. Please let me know if any issues come up.

**Comment by gdelmas** [comment]
@trollixx thanks for the info. ideally i wanted to check the registry and change the icon and label according to which application is registered to the url handler. i will keep this open to remember it.

**Comment by lusitania** [comment]
So, what's the current state? Is Zeal now supported or do I have to tweak something myself? If my intervention is required please hint were us Zeal users should start digging.

Best

**Comment by gdelmas** [comment]
hi @lusitania,

did you try it? as far as i understand @trollixx implemented full protocol support with zeal version 0.1.0. so it should be supported.

the only thing i still might need to do, is change the text label in the ui. please let me know if it works.

**Comment by lusitania** [comment]
@gdelmas, you were right. The integration is indeed working properly. There are some issues however I assume those originate from Zeal itself (not gaining focus, staying in the background and stuff).

Thank you

**Comment by gdelmas** [comment]
@lusitania, you are correct. zeal has to gain the focus. i suggest you file an issue with zeal. @trollixx has been great in supporting windows so far.
