### ISSUE TITLE
Dash Plugin Error with Velocity

### ISSUE THREAD

**Issue by drohm** [gdelmas/IntelliJDashPlugin#39]
I installed the 3.2.2 version of the plugin in PyCharm 4.0.4 (Windows 8.1 x64), no issues or errors.  When I try to "Search in Velocity" I get the following error:

```
Dash Plugin Error
           Failed to open dash-plugin://keys=python3,python,django,twisted,sphinx,flask,tornado,sqlalchemy,numpy,scipy,salt,cvp&query=getLogger. Error message: A device attached to the system is not functioning.
```

I have Velocity 1.0.5 installed (licensed).  I've tried uninstalling and reinstalling Velocity and also removing and adding the Dash plugin again.  Both didn't work.  I'm not sure what else to try.

**Comment by gdelmas** [comment]
can you please try the url from a browser and/or the open with dialog

`dash-plugin://keys=python3,python,django,twisted,sphinx,flask,tornado,sqlalchemy,numpy,scipy,salt,cvp&query=getLogger`

please also try:

`dash-plugin://keys=python3&query=getLogger`

**Comment by drohm** [comment]
I'm getting "Application not found" for both suggestions.  Doesn't work in the browser either (Chrome or IE).  Should the install of Velocity have created a registry entry or something for 'dash-plugin://' protocol so that it knows to launch Velocity?

**Comment by gdelmas** [comment]
yes it should have. although i don't know if modern windows versions allow to open the protocols from browsers or the open dialog. but i suspect that the protocol is not registered correctly from the plugin error.

maybe you can try to register it manually. [here](https://github.com/zealdocs/zeal/issues/247) is a description for how zeal would have registered it.

**Comment by drohm** [comment]
I'm all set.  The author of Velocity sent me a couple reg files to create the necessary registry entries and everything is launching fine from PyCharm via the plugin.  Thanks.

**Comment by kanytu** [comment]
Would be cool if someone share the reg files instead of closing the issue

**Comment by drohm** [comment]
Email the author.  He's more than willing to help.

**Comment by gdelmas** [comment]
@kanytu this is a velocity issue, therefore it is closed on the plugin's bugtracker. but you can gladly share the regfiles for any other who might be looking for them.

**Comment by sakuyayc** [comment]
@drohm if you can share the reg files, that will be nice.

**Comment by drohm** [comment]
The author sent me two registry files to run:

**dash-plugin**
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\dash-plugin]
@="Velocity Search (Dash Plugin Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash-plugin\DefaultIcon]
@="C:\\Program Files (x86)\\Silverlake Software LLC\\Velocity\\Velocity.exe,1"

[HKEY_CLASSES_ROOT\dash-plugin\shell]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open\command]
@="\"C:\\Program Files (x86)\\Silverlake Software LLC\\Velocity\\Velocity.exe\" -url \"%1\""
```

**dash**
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\dash]
@="Velocity Search (Dash Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash\DefaultIcon]
@="C:\\Program Files (x86)\\Silverlake Software LLC\\Velocity\\Velocity.exe,1"

[HKEY_CLASSES_ROOT\dash\shell]

[HKEY_CLASSES_ROOT\dash\shell\open]

[HKEY_CLASSES_ROOT\dash\shell\open\command]
@="\"C:\\Program Files (x86)\\Silverlake Software LLC\\Velocity\\Velocity.exe\" -url \"%1\""
```

Save these to .reg files and run them.  These worked for me.

**Comment by Vouskopes** [comment]
@drohm Thx. I also had this trouble.
@gdelmas It might have been convenient to display this at last on project main page.

**Comment by liutf** [comment]
@drohm  Thx!

**Comment by etiennejcharles** [comment]
Is there a reason why this is closed ? ~ Bug still occurs as of today

**Comment by gdelmas** [comment]
@etiennejcharles this seems to be a velocity bug.

please see: https://github.com/gdelmas/IntelliJDashPlugin/issues/39#issuecomment-164648562

**Comment by gdelmas** [comment]
this is a velocity issue because velocity needs to register some url handlers to be available to third party integrations like this plugin.

**Comment by gdelmas** [comment]
i assume velocity usually registers the above mentioned url handlers for third party integrations to work. maybe there is some issue with that?

what do you think, @jdasilva

**Comment by jdasilva** [comment]
As far as I know Velocity does what it should according to the Windows guidelines.  In the handful of cases where I got more information Zeal was installed prior to Velocity.  If someone has had this problem under different circumstances, please let me know because then I'm missing something!

I will look into if there is more I can for detecting and correcting this.
