### ISSUE TITLE
has

### ISSUE THREAD

**Issue by qq308745107** [gdelmas/IntelliJDashPlugin#40]

**Comment by qq308745107** [comment]
intellj idea occur error : 
class with name "de.dreamlab.dash.DashLauncherAction" not found [Plugin: com.paperetto.dash]

**Comment by gdelmas** [comment]
could you please tell more details.

- the full stacktrace
- which version of the plugin are you using?
- where did you install the plugin from (repository/manual)?
- which operating system are you using?
- did the plugin work before? or did you just install it?
- is the error reported each time you invoke the shortcut or just once?
- is there an error report upon ide startup (please check event window)

**Comment by qq308745107** [comment]
may i config hotkey ,i can't ensure what reason. then reinstall ver 3.2.2 ， it's ok now .all right. thank you .
