### ISSUE TITLE
How do I add a custom docsets support?

### ISSUE THREAD

**Issue by tofuliang** [gdelmas/IntelliJDashPlugin#42]
It seems IntelliJDashPlugin just support  

php,wordpress,drupal,zend,laravel,yii,joomla,ee,codeigniter,cakephp,phpunit,symfony,typo3,twig,smarty,phpp in PHPSTORM

But if I have my own docsets,how do I add it to IntelliJDashPlugin?

**Comment by gdelmas** [comment]
if it is a custom docset you added through "Php Docsets (packagist.org)" it should also be supported.

if you created a custom docset yourself you can set `DocSetPlatformFamily` to `php`. it should be found aswell.

otherwise you can fork the plugin and add the missing docset.

**Comment by Kapeli** [comment]
Don't set `DocSetPlatformFamily` to `php` as that will make Dash believe it's the actual PHP docset. Set `DashDocSetPluginKeyword` to `php` instead.

**Comment by tofuliang** [comment]
I am using ZEAL under Windows,but both these solution did not work for me.

Bogdan Popescu <notifications@github.com>于2015年6月12日周五 下午8:58写道：

**Comment by gdelmas** [comment]
than you might have to use the third solution and fork the plugin.

you might also want to raise an issue with the zeal developers that `DashDocSetPluginKeyword` does not work.
