### ISSUE TITLE
JetBrains letter

### ISSUE THREAD

**Issue by Kapeli** [gdelmas/IntelliJDashPlugin#46]
I don't think the top of the README is the right place to have that. It makes things kind of unusable as-is.

Dash will stop linking to this repo and link to https://github.com/Kapeli/IntelliJDashPlugin#readme instead for the time being.

**Comment by gdelmas** [comment]
i could move it under usage, it this is okay for you. 
this is an important issue, a lot of jetbrains customers are expressing there disappointment right now. if nothing is said at this point we might have another adobe case, where a company no longer has any monetary incentive to do important changes and bugfixes.

**Comment by Kapeli** [comment]
In my opinion it would be best if you'd move it at the very bottom and just have a short unobtrusive message at the top that links to it.

**Comment by gdelmas** [comment]
okay. i did that. hope you will link back. 
hopefully the licensing situation will change back pretty quick. they could or should have just raised the prices. subscriptions are really sad.

**Comment by Kapeli** [comment]
Looks good. I've changed back. Thanks for understanding.

**Comment by gdelmas** [comment]
as a designer i understand the unfriendly user perspective of the readme very well.

thanks for also understanding the importance of the licensing change. hope you have a similar opinion on the topic.
