### ISSUE TITLE
When using Zeal, Java documentation cannot be shown because the docset is named differently

### ISSUE THREAD

**Issue by michel-slm** [gdelmas/IntelliJDashPlugin#47]
the Dash plugin specifies `javaN` (where N is the JDK version) but the docsets available in Zeal are tagged `java se7`, `java se8` etc.

Perhaps the dash plugin could add these to the list of docsets it's searching in?

**Comment by gdelmas** [comment]
please read issue #44

**Comment by michel-slm** [comment]
Aha, thanks, following it on the Zeal tracker.
