### ISSUE TITLE
How can I set default docset for specific language?

### ISSUE THREAD

**Issue by ooopscc** [gdelmas/IntelliJDashPlugin#48]
For example, 

- Objective-C or .m extension -> iOS (docset)
- .js extension -> JavaScript, jQuery (may use search profile)

Because, I have many docsets in Dash, search all docsets leads very slow.

**Comment by gdelmas** [comment]
the file extensions are already mapped to the correct docsets. it already works like the two examples you provided

> The plugin either searches for the statement at caret position or the current selection. It will identify the programming language in use and request filtered results accordingly.

**Comment by ooopscc** [comment]
But it doesn't seem to work for me.
I use AppCode for Mac, placed caret to `UITableView`
Press `Command-Shift-D`, Dash show up, but it search all docset without any filters.

What may be wrong?

**Comment by gdelmas** [comment]
the appcode team did implement their own method to open dash. therefore objective-c syntax and appcode file mappings are not supported. that is why this plugins documentation does not state appcode support.

of course you can still use the plugin for javascript, html, etc. just objective-c and swift are not supported. for that you should use appcodes native dash support.

see Dashs Settings Integration Tab for how to enable it.

**Comment by ooopscc** [comment]
Thanks anyway. I switch off Dash Plugin, use Dash as External Documentation still search in all docsets.

**Comment by gdelmas** [comment]
that's bad. maybe you can file an issue with the appcode team. i will also review the issue in future versions of the plugin and maybe decide to support appcode as well.

**Comment by ooopscc** [comment]
That's great if you support appcode. I will fire an issue. Thanks a lot.
