### ISSUE TITLE
Search hits  should be ordered according to file's context

### ISSUE THREAD

**Issue by lusitania** [gdelmas/IntelliJDashPlugin#49]
Hi

When searching for a word in PyCharm, i.e. ``FROM`` in a Dockerfile, I'm correctly being sent to Zeal. The first result however is from Python's include statement ``from module include name``. Only the second result is about Docker.

I've reported this in [zeal issue 441](https://github.com/zealdocs/zeal/issues/441), @trollixx thinks this is closer to your domain.

Best

**Comment by gdelmas** [comment]
i released a [new version](https://github.com/gdelmas/IntelliJDashPlugin/releases/tag/3.2.4) with a definition for the dockerfile context. i also included bash and manpages docs in this case. i do not get details about the elements inside the dockerfile and suppose some cli tools might be used within the dockerfile. the other docsets have lower priority though. i don't know if zeal respects this order. it looks like dash does not.

please also install the docker plugin from the jetbrains repository for this feature to work.

**Comment by Kapeli** [comment]
> it looks like dash does not.

What `dash-plugin` URL do you call and Dash doesn't respect the order?

**Comment by gdelmas** [comment]
i am not sure, if you prioritize the search results by keyword order. i think i remember that you once told me dash didn't.

for example:
i would assume this query shows the manpage entry first

    open -g dash-plugin://keys=manpages,php\&query=from

where as this query would show the php documentation entry first

    open -g dash-plugin://keys=php,manpages\&query=from

however dash shows the php result first in both cases.

**Comment by Kapeli** [comment]
Ah. I see. Type ordering takes precedence over docset ordering. So PHP Methods show up above Man Pages which are indexed as Functions, regardless of the docset order.

Type ordering works great when the docsets you search over are similar in types, but fails when not. Kind of working as intended.

**Comment by gdelmas** [comment]
i see. this explains the same behavior when searching in docker and man pages. the docker entry is marked as section, whereas the man entry is marked as function. i guess additionally the docker entry also just qualifies as partial match. 

for example:

    open -g dash-plugin://keys=docker,bash,manpages\&query=from

thanks for clarifying @Kapeli

**Comment by lusitania** [comment]
Already done? Wow you are fast!

There are two Docker plugins available for PyCharm:
 - Docker for Python
 - Docker integration

I've installed both, not knowing if I'll be breaking anything. Do you recommend one over the other?

**Comment by gdelmas** [comment]
hi peter,

i just tired the jetbrains docker plugin. i guess this is the latter one. it would be interesting to know if it also just works with the former one installed.

if you do try and it does not work, please tell me what the status bar states when you invoke the dash lookup.

i just need the plugin to recognize the language of the file (context). apart from that i can not say anything about there features.
