### ISSUE TITLE
Giving focus to Dash when running a trial

### ISSUE THREAD

**Issue by IT2BE** [gdelmas/IntelliJDashPlugin#50]
Hi,

When I first used the plugin I could go to Dash using the key code for it.
Now this does not work anymore.

Using the tools menu everything is ok.

I think it may have to do with the delay I see before something shows (I am running a trial version of Dash). I suspect that this does something with the focus as well...

**Comment by gdelmas** [comment]
@kapeli might this be a dash issue?

**Comment by Kapeli** [comment]
So it works when you use the plugin from the Tools menu and doesn't work when you use the keyword shortcut?

It's definitely not a trial/delay issue. The trial doesn't interfere with window activation at all.

My best guess of what might be going on would be that you've set the same keyword shortcut for Dash in Preferences > General, so the plugin would activate Dash and immediately after Dash would deactivate itself.

If you use the plugin using the keyword shortcut, does the search query in Dash change at all? If it doesn't, it would mean that the plugin isn't sending anything to Dash.

**Comment by IT2BE** [comment]
OK, this is what I see (exactly):

- Select item -> Menu -> Tools -> Search in Dash -> Shows Dash and searches for the selected item
- Select item <command><shift><d> briefly highlights the Tools menu item and does nothing

So, in the first case the search is effective and ok
In the second case Dash does not show up and the search is not activated so it seems.

Ciao,

Marcel Trapman
marceltrapman@me.com

**Comment by Kapeli** [comment]
So most likely Dash doesn't get called at all.

Maybe you have something else in the Tools menu that uses that shortcut and that gets called instead?

**Comment by gdelmas** [comment]
please check the ide's status bar after invoking the shortcut. does it state "Searching ... docsets in Dash". otherwise you might have assigned some other action to the shortcuts as @Kapeli suggested.

**Comment by IT2BE** [comment]
And that did the trick.

Out of curiosity I removed and re-added the shortcut.

It mentioned the UML plugin.

I decided to change the shortcut to <control><option><command><d> and made it work again.

Thanks for your support (and this could be worth mentioning).


Ciao,

Marcel Trapman
marceltrapman@me.com
