### ISSUE TITLE
Dash plugin cannot be found using PyCharm 5.0.4

### ISSUE THREAD

**Issue by ssbarnea** [gdelmas/IntelliJDashPlugin#51]
Dash plugin cannot be found using PyCharm 5.0.4

**Comment by gdelmas** [comment]
i can not reproduce this. can you please post a screenshot of the plugin missing in the repository.

**Comment by ssbarnea** [comment]
Sorry, my mistake, probably I should raise a bug with JetBrains as they managed to make the plugin discovery so awkward.
