### ISSUE TITLE
Recognise Elixir

### ISSUE THREAD

**Issue by smeevil** [gdelmas/IntelliJDashPlugin#53]
Hi,

First of thank you so much for creating this plugin, it is really a huge time safer for me :D
I noticed that it does not recognise Elixir yet as language, and was wondering if you could add support for this!

Much appreciated,

Gerard

**Comment by gdelmas** [comment]
what is the elexir code support plugin people are using?

it it this: https://github.com/KronicDeth/intellij-elixir ?

**Comment by smeevil** [comment]
Yes indeed

**Comment by smeevil** [comment]
Was wondering if there is any progress on this or if there is anything that I can do to help ?

**Comment by smeevil** [comment]
Anything that i can do to help ?

**Comment by gdelmas** [comment]
you can check the plugins keyword by modifying this line: https://github.com/gdelmas/IntelliJDashPlugin/blob/master/src/de/dreamlab/dash/DashLauncherAction.java#L150

than you can add the keyword here: https://github.com/gdelmas/IntelliJDashPlugin/blob/master/src/de/dreamlab/dash/KeywordLookup.java
