### ISSUE TITLE
unstub Search in Dash issue

### ISSUE THREAD

**Issue by andixtaf** [gdelmas/IntelliJDashPlugin#56]
After Installing Dash version 3.2.3 and an update to version 3.2.4 from this git repository intelliJ throws following error:

Can't unstub Search in Dash (Searches word under caret or selected text in Dash) 
java.lang.Throwable

[idea.txt](https://github.com/gdelmas/IntelliJDashPlugin/files/605903/idea.txt)

This Behavior doesn't appear if i uninstall / reinstall this plugin.

**Comment by gdelmas** [comment]
hi @andixtaf,

so once the plugin has been uninstalled the unstub error does not appear? also if you install another version over the plugin?

could you please tell me some more details.

- which version of the which ide are you using?
- you did install the plugin from the repo (3.2.3) and manually (3.2.4), right?
- which operating system are you using?
- did the plugin work before? or did you just install it?
- is the error reported each time you invoke the shortcut or just once?
- is there an error report upon ide startup (please check event window)

**Comment by andixtaf** [comment]
hi @gdelmas,

this is correct, if i uninstall the plugin the error message won't appear.

- i use IntelliJ Ultimate 2016.3 () few days ago 2016.2 had the same issue)
- Ubuntu 16.04 (Kubuntu)

IntelliJ IDEA 2016.3  Build #IU-163.7743.44 
 JDK: 1.8.0_112-release 
 VM: OpenJDK 64-Bit Server VM 

The error is reproducable and every time i invoke the shortcut or open Tools in the menu bar the error is reported in the idea.log file

error report says:
class with name 'de.dreamlab.dash.DashLauncherAction' not found [Plugin: com.paperetto.dash]

[err.txt](https://github.com/gdelmas/IntelliJDashPlugin/files/619244/err.txt)

greetings

**Comment by gdelmas** [comment]
hi @andixtaf,

i don't have a ubuntu linux system setup to test at the moment. the call stack seems to be entirely from idea. are other third party plugins working? also manually installed ones?
