### ISSUE TITLE
Keyboard shortcut not behaving properly

### ISSUE THREAD

**Issue by robtcallahan** [gdelmas/IntelliJDashPlugin#59]
Hi,

What I’ve found using the Intellij Idea plugin, is that the keyboard shortcut does not perform a search. It opens up Dash but nothing is entered into the search field. However, if I use the Tools menu option it works correctly. Any idea why this would be? I cannot tell what version I have of Dash. I have Mac OS 10.12 and Idea 2016.3. I appreciate any help you can provide.

**Comment by gdelmas** [comment]
could you please tell me some more details.

- which version of the plugin are you using?
- where did you install the plugin from (repository/manual)?
- did the plugin work before? or did you just install it?
- is there an error report upon ide startup (please check event window)
- what is stated in the ide status bar after you invoke the plugin
- why can't you tell the dash version?

**Comment by robtcallahan** [comment]
Hi,

I just restarted Idea to answer one of the questions and it’s now working.
Sorry to bother you. Love the product.

Have a good weekend,
Rob


Rob Callahan
Senior Software Engineer
APX Labs
2350 Corporate Park Drive, Ste. 400 | Herndon VA 20171
m: 240-350-2235 | t: @JeffEJenkins | www.apx-labs.com<http://www.apx-labs.com>

On Dec 16, 2016, at 11:37 AM, Gerard Delmàs <notifications@github.com<mailto:notifications@github.com>> wrote:


could you please tell me some more details.

  *   which version of the plugin are you using?
  *   where did you install the plugin from (repository/manual)?
  *   did the plugin work before? or did you just install it?
  *   is there an error report upon ide startup (please check event window)
  *   what is stated in the ide status bar after you invoke the plugin
  *   why can't you tell the dash version?
