### ISSUE TITLE
No Dash in plugins repository PhpStorm 

### ISSUE THREAD

**Issue by Triloworld** [gdelmas/IntelliJDashPlugin#60]
Hello,
No repository called Dash ;(
Installed manually and it's working just fine.
Can you check it?

PhpStorm 2016.3
Build #PS-163.7743.50, built on November 22, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by gdelmas** [comment]
i have checked. have you clicked on **Preferences -> Plugins -> Browse repositories**?

**NOT Install JetBrains plugin...**

**Comment by Triloworld** [comment]
Thx. I updated PhpStorm to 2016.3.2 and working fine. Just to know that img don't display in description. Thx for reply 👍 If something is wrong then installing manual work just fine.
