### ISSUE TITLE
Add Tapestry support

### ISSUE THREAD

**Issue by hhubris** [gdelmas/IntelliJDashPlugin#62]
Tapestry has html templates, supported by the Tapestry Support plugin.  If this could be linked to the HTML docset that would be very helpful.

**Comment by gdelmas** [comment]
hi @hhubris. sorry for the late reply.

which tapestry plugin are you referring to. i see three:
  - HandyTapestry (http://handyedit.com/handytapestry.html)
  - Tapestry 4.1 (https://github.com/aholowko/intellij-tapestry4)
  - Tapestry 4.1 Support (http://www.mjava.ch)

does the ide provide autocompletion when writing HTML in the template? this should automatically establish a html context for the lookup.
