### ISSUE TITLE
Add option to choose appropriate application

### ISSUE THREAD

**Issue by Kimi-Arthur** [gdelmas/IntelliJDashPlugin#65]
For example, on Windows you have multiple choices like Zeal, Velocity.

Also there are websites like devdocs.io which support similar pattern. So if we have the option, we may be able to support this type of documentation tool.

**Comment by gdelmas** [comment]
as far as i know, devdocs.io does not support multiple filters, therefore a context aware search from the plugin might not be of great help.

to open devdocs.io from the editor you can configure an external tool in the ide: https://github.com/gdelmas/IntelliJDashPlugin/issues/28#issuecomment-50283439

**Comment by gdelmas** [comment]
on windows and linux the plugin uses the application that registered the dash-plugin:// url scheme. i assume this is the last application installed. the applications might also provide options to re-register this scheme.

see: https://github.com/gdelmas/IntelliJDashPlugin/issues/36
