### ISSUE TITLE
Define where to search

### ISSUE THREAD

**Issue by a-d-p** [gdelmas/IntelliJDashPlugin#67]
Hi, thanks a lot for this plugin. I have one question. Is possible to define in which docs to search similarly like in SublimeText plugin (e.g. 'python':'python3,numpy,scipy,matplotlib')?

**Comment by gdelmas** [comment]
hi @a-d-p,

the keywords are hardcoded into the plugin. if the addition of keywords makes sense for all users, i can add them. as far as i remember there is also some mechanic in dash that matches docsets with the correct language.

the current python keywords are here: https://github.com/gdelmas/IntelliJDashPlugin/blob/402f2c8399b15d5a6ae9311b24bc19c61c374d04/src/de/dreamlab/dash/KeywordLookup.java#L64

**Comment by a-d-p** [comment]
Hi. Thanks a lot for the answer. Personally, I miss search in matplotlib for python.
