### ISSUE TITLE
Using 3.3 Zeal (Windows) doesn't open

### ISSUE THREAD

**Issue by gsc89** [gdelmas/IntelliJDashPlugin#69]
I see in the change log this was supposed to be fixed but I get the following with Zeal installed and using the shortcut.

![image](https://user-images.githubusercontent.com/1032459/34940021-e72bb834-f9e5-11e7-89d7-5d8aa54c250a.png)

Can anyone help I would like to be able to use this if I can.

**Comment by gdelmas** [comment]
have you checked if a `dash-plugin://` URI opens Zeal from other programs. you might be able to test this from the browser or maybe the run menu.

**Comment by gsc89** [comment]
It does not, no.

I simply installed zeal downloaded some docs and installed this plugin, I didn't see any setup mentioned for the URI to work, did I miss something?

**Comment by gdelmas** [comment]
this means zeal has not registered the URL handler. please see check if https://github.com/zealdocs/zeal/issues/247#issuecomment-75353195 on the zeal tracker helps.
