### ISSUE TITLE
Application not found - win7, PyCharm-2018.2.4, zeal-0.6.1

### ISSUE THREAD

**Issue by emcek** [gdelmas/IntelliJDashPlugin#75]
```
PyCharm 2018.2.4
Build #PY-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```
```
4:13 PM	Dash Plugin Error
Failed to open dash-plugin://keys=python3,python,django,twisted,sphinx,flask,tornado,sqlalchemy,numpy,scipy,salt,cvp,matplotlib&query=sorted. Error message: Application not found
```
I've reinstall Dash plugin as well as zeal-0.6.1. It stop working. Can I provide any more logs?? With the same tools at linux its working.

**Comment by gdelmas** [comment]
looks like Zeal is not registered correctly. try this: https://github.com/gdelmas/IntelliJDashPlugin#on-windows-when-using-zeal-the-ide-shows-failed-to-open-dash-plugin-in-the-event-log
