### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by erakli** [gdelmas/IntelliJDashPlugin#76]
Hi,

Is there any possibility to customize plugin? For example, based on project or language. I have 2 cases:

1. Search for function in python code performed among all python frameworks (also, that are not installed in docsets). Here's search for string `join` function, that I got in Zeal:

    ```
    python3,python,django,twisted,sphinx,flask,tornado,sqlalchemy,numpy,scipy,salt,cvp,matplotlib:about
    ```

2. I have to use PyQt5 and there's no convenient in-line documentation presented. PyQt5 documentation mostly links to Qt site. Thus, if I want to look-up something about Qt function, I ought to search Qt documentation instead. There's difficulty - Qt is written in C++ notation (ClassName::methodName), while python search performed in another way (classname.methodname).

Can we do something with these cases? For example, create custom rules for specific situations?

**Comment by gdelmas** [comment]
hey @erakli,

1. it is correct that the filters passed to your documentation browser include a list of frameworks that are expected to be used in the given language. not installed docsets should not cause any trouble and will be ignored. your documentation browser should sort results in order of the keys passed. this way a result from the python documentation should be the first result, as `python3` and `python` are the first two keys.

2. transforming the query passed to your documentation browser would be out of scope for this plugin. yet when you actively select the word you are searching for, this will be the only term passed to your documentation browser.

there is also the option to not use language detection by selecting "Search all Documentation in ..." from the Tools menu.

**Comment by Mnaukal** [comment]
Is it possible to configure the filter? I would like to add other keys to the search, for example "TensorFlow-2.1" for my ".py" files.
