### ISSUE TITLE
How do I "dash" to the right place on my computer?

### ISSUE THREAD

**Issue by evanricard** [gdelmas/IntelliJDashPlugin#78]
Hey gdelmas,

I just have a question regarding a scenario involving this plugin and two installations of separate (but equal) documentation viewers. For clarification, I am on a Windows machine and I have an installation of Zeal as well as Velocity. I have recently adopted the Jetbrains suite of software into my life and I want to only use Velocity straight from the Jetbrains IDE (Rider). 

I am unsure of how to configure my environment to only point at Velocity. Any help would be greatly appreciated, thanks!

**Comment by gdelmas** [comment]
hey @evanricard,

sorry for the late reply. on windows and linux the plugin uses the application that registered the dash-plugin:// url scheme. i assume this is the last application installed. the applications might also provide options to re-register this scheme.

have a look at: https://github.com/gdelmas/IntelliJDashPlugin/issues/39#issuecomment-164648562
