### ISSUE TITLE
@cursor in code snippets do not work in IntelliJ idea

### ISSUE THREAD

**Issue by superbaobei** [gdelmas/IntelliJDashPlugin#82]
I install this plugin in my idea,and then I type my first  test snippet in dash ,what I type as follow:
`    public void test() {
        System.out.println("test");
    }@cursor
`
What I want is when I type `test` in idea,then the cursor will in the last location of this snippet.But it is not the case,what I get is 
![image](https://user-images.githubusercontent.com/20183521/64938289-fc84df00-d88f-11e9-9464-d2929de1922e.png),the cursor is in Dash's search text,how can I fix this ?help me

**Comment by gdelmas** [comment]
This plugin only provides reference lookups in Dash. It does not handle any snippet features, either provider by Dash or Idea.
